name: Build and Install

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build-and-install:
    permissions:
      contents: read
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-tidy-21

      - name: Generate make files
        run: sudo cmake -S. -DCMAKE_INSTALL_PREFIX=/usr/ -Bbuild -DCMAKE_CXX_CLANG_TIDY=clang-tidy

      - name: Build the project (and lint it with clang-tidy)
        run: sudo cmake --build build -j8

      - name: Install the project
        run: sudo cmake --build build --target install -j8

      - name: Verify installation
        run: |
          ls /usr/include/libROOT | grep -E 'root.hpp|dummy_class.hpp'
          file /usr/bin/root_cli
          file /usr/lib/libROOT.so
          root_cli
